spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
