server:
  port: 7001 #(eureka 默认端口为：8761)

spring:
  application:
    name: platform-eureka #服务名
#  security:
#    basic:
#      enabled: true # 开启基于HTTP basic的认证
#    user:
#      name: admin  # 配置登录的账号是admin
#      password: 123456 #配置登录的密码是 123456

eureka:
  instance:
    #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    leaseExpirationDurationInSeconds: 15
    hostname: ${eureka.instance.ip-address}
    instanceId: ${eureka.instance.ip-address}:${server.port}
    preferIpAddress: true     #将IP注册到Eureka Server上
  client:
    #是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    registerWithEureka: false
    fetchRegistry: false      #表示是否从eureka服务器获取注册信息
    serviceUrl:
      #是设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址（注意：地址最后面的 /eureka/ 这个是固定值）
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    #设为false，关闭自我保护，开发测试环境需要频繁启动注册实例，需要关闭自我保护功能，以免请求跑到旧实例中，生成环境需要开启自我保护功能
    enableSelfPreservation: false
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 5000
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eureka.server.evictionIntervalTimerInMs: 20000