server:
  port: 7081

spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 2
      minIdle: 2
      maxActive: 10
      maxWait: 3000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      validationQuery: SELECT 1
      validationQueryTimeout: 5
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
eureka:
  instance:
    ip-address: 127.0.0.1
    registry.default-open-for-traffic-count: 1                             # 注册实例
    registry.expected-number-of-renews-per-min: 1                          # 注册实例
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"