spring:
  application:
    name: platform-eureka

---
server:
  port: 7001
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:7001
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7002/eureka/
  server:
    enable-self-preservation: false

---
server:
  port: 7002
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:7002
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    enable-self-preservation: false
